apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: nginx-secrets
  namespace: frontend
spec:
  backendType: secretsManager
  region: ap-south-2
  dataFrom:
    - nginx-secrets