apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend

commonLabels:
  env: stage
  owner: gray
  application: nginx
  
resources:
- ../bases
- external-secret.yaml

patchesStrategicMerge:
  - service.yaml
  - deployment.yaml